name: Streamlit CI

on: push

jobs:
  streamlit:
    runs-on: ubuntu-latest

    # Permissions for Github OIDC Token for google auth action
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      # Enable gcloud ADC in workflow through workload identity federation
      - uses: 'google-github-actions/auth@v3'
        with:
          # TODO: Setup CI specific project and workload identity federation
          project_id: 'next25-workshop'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDP }}'

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # The app requires access to the secrets for init
      - name: Create .streamlit/secrets.toml file
        run: |
          echo ${{ secrets.BASE64_SECRETS_TOML }} | base64 -d > .streamlit/secrets.toml

      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: app.py
